module.exports = {
    LOAD: 'LOAD',
    LOAD_ERROR: 'LOAD_ERROR',
    LOAD_SUCCESS: 'LOAD_SUCCESS',
    LOAD_WINE: 'LOAD_WINE',
    LOAD_WINE_SUCCESS: 'LOAD_WINE_SUCCESS',
    LOAD_WINE_ERROR: 'LOAD_WINE_ERROR',
    CREATE_WINE: 'CREATE_WINE',
    CREATE_WINE_SUCCESS: 'CREATE_WINE_SUCCESS',
    CREATE_WINE_ERROR: 'CREATE_WINE_ERROR',
    UPDATE_WINE: 'UPDATE_WINE',
    UPDATE_WINE_SUCCESS: 'UPDATE_WINE_SUCCESS',
    UPDATE_WINE_ERROR: 'UPDATE_WINE_ERROR',
    DELETE_WINE: 'DELETE_WINE',
    DELETE_WINE_SUCCESS: 'DELETE_WINE_SUCCESS',
    DELETE_WINE_ERROR: 'DELETE_WINE_ERROR'
};
