module.exports = {
    LOAD: 'LOAD',
    LOAD_ERROR: 'LOAD_ERROR',
    LOAD_SUCCESS: 'LOAD_SUCCESS',
    LOAD_WINE: 'LOAD_WINE',
    LOAD_WINE_SUCCESS: 'LOAD_WINE_SUCCESS',
    LOAD_WINE_ERROR: 'LOAD_WINE_ERROR',
    CREATE: 'CREATE',
    DELETE: 'DELETE'
};
